name: CI-CD

on:
  push:
    branches:
      - main
      
env:
  S3_BUCKET_NAME: s3-ebnatural
  RESOURCE_PATH: ./src/main/resources/application-prod.yaml
  CODE_DEPLOY_APPLICATION_NAME: CODE-DEPLOY-EBNATURAL
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: CODE-DEPLOY-GROUP
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

#      - name: Set yaml file
#        uses: microsoft/variable-substitution@v1
#        with:
#          files: ${{ env.RESOURCE_PATH }}
#        env:
#          spring.datasource.url: ${{ secrets.RDS_HOST }}
#          spring.datasource.username: ${{ secrets.RDS_USERNAME }}
#          spring.datasource.password: ${{ secrets.RDS_PASSWORD }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: clean build -x test

      - name: Make Directory
        run: mkdir -p deploy

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      - name: Make zip file
        run: zip -r ./work.zip ./deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./work.zip s3://$S3_BUCKET_NAME/

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=work.zip \
          --region ap-northeast-2
